### ISSUE TITLE
android:supportsRtl="true"

### ISSUE THREAD

**Issue by pishguy** [Kishanjvaghela/Ask-Permission#7]
please remove this line from manifest

**Comment by Kishanjvaghela** [comment]
@MahdiPishguy  Is there any problem?

**Comment by pishguy** [comment]
@Kishanjvaghela yes, when i desing right to left view, that cause of change when i change phone language. for example i want to have fixed layout for all languages, i have to download library source code

**Comment by Kishanjvaghela** [comment]
You can add

tools:replace="android:supportsRtl"

Example
`
<application 
android:label="@string/app_name"
android:supportsRtl="true"
tools:replace="android:supportsRtl"/> `

**Comment by Kishanjvaghela** [comment]
Example 

<application 
android:label="@string/app_name"
android:supportsRtl="true"
tools:replace="android:supportsRtl"/>
